In [14]:
from torchvision import models
import torch

In [15]:
vgg = models.vgg16_bn(pretrained=False)

In [84]:
a = 3//2 
import numpy as np
def bilinear_kernel(in_channels, out_channels, kernel_size):
    factor = (kernel_size + 1) // 2
    if kernel_size % 2 == 1:
        center = factor - 1
    else:
        center = factor - 0.5
    print("factor is: ", factor)
    print("kernel is: ", kernel_size)
    print("center: ", center)
    og = np.ogrid[:kernel_size, :kernel_size]
    print(og)
    print("xx:",1-abs(og[0]-center)/factor)
    bilinear_filter = (1 - abs(og[0] - center) / factor) * (1 - abs(og[1] - center) / factor)
    print("bilinear_filter", bilinear_filter)
    weight = np.zeros((in_channels, out_channels, kernel_size, kernel_size), dtype=np.float32)
    print(range(in_channels))
    l = np.array([i for i in range(10)])
    #print("l is: ", l)
    #print(weight)
    weight[range(in_channels), range(out_channels), :, :] = bilinear_filter
    #weight[0,0,:,:] = bilinear_filter
    #weight[1,1,:,:] = bilinear_filter
    print("xxxxxxx",bilinear_filter)
    
    #print("xxxx")
    d = np.zeros((3,3,2,2))
    print(d)
    d[range(3),range(3),:,:] = [[1,2],[3,4]]
    print(d)
    return torch.from_numpy(weight)
bilinear_kernel(3,3,2)

factor is:  1
kernel is:  2
center:  0.5
[array([[0],
       [1]]), array([[0, 1]])]
xx: [[0.5]
 [0.5]]
bilinear_filter [[0.25 0.25]
 [0.25 0.25]]
range(0, 3)
xxxxxxx [[0.25 0.25]
 [0.25 0.25]]
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[[[1. 2.]
   [3. 4.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[1. 2.]
   [3. 4.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[1. 2.]
   [3. 4.]]]]


tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.2500, 0.2500],
          [0.2500, 0.2500]]]])

tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.2500, 0.2500],
          [0.2500, 0.2500]]]])

In [30]:
print(x[0].shape)
x[1].shape


(3, 1)


(1, 3)

NameError: name 'og' is not defined